version: "3.8"
services:
  api:
    container_name: lifeapp-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    networks:
      - lifeapp-network
    depends_on:
      - mongo

  frontend:
    container_name: lifeapp-frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro  # Mount your custom Nginx configuration
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount your Let's Encrypt certificates
    networks:
      - lifeapp-network


  mongo:
    image: mongo
    container_name: lifeapp-mongo
    ports:
      - "27017-27019:27017-27019"
    networks:
      - lifeapp-network      

networks:
  lifeapp-network:
    name: lifeapp-network
    driver: bridge
