version: '3.8'

# Other services are not needed, since we are using ng serve (Angular Frontend) npm run (NodeJS Backend)

services:
  mongo:
    image: mongo
    container_name: lifeapp-mongo
    ports:
      - "27017:27017"
    networks:
      - lifeapp-network

networks:
  lifeapp-network:
    name: lifeapp-network
