version: "3.6"
services:
  api:
    container_name: lifeapp-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    networks:
      - lifeapp-network
    depends_on:
      - mongo
      - frontend
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', res => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 10s
      timeout: 5s
      retries: 20

  frontend:
    container_name: lifeapp-frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - lifeapp-network

  mongo:
    image: mongo
    container_name: lifeapp-mongo
    ports:
      - "27017-27019:27017-27019"
    networks:
      - lifeapp-network

  playwright:
    container_name: playwright-test
    environment:
      - PWDEBUG=1
    build:
      context: ./playwright
      dockerfile: Dockerfile
    depends_on:
      api:
        condition: service_healthy 
    networks:
      - lifeapp-network

networks:
  lifeapp-network:
    name: lifeapp-network
    driver: bridge