version: "3.8"
services:
  api:
    container_name: lifeapp-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    networks:
      lifeapp-network:
        ipv4_address: 10.130.210.1
    depends_on:
      - mongo

  frontend:
    container_name: lifeapp-frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      lifeapp-network:
        ipv4_address: 10.130.210.2

  mongo:
    image: mongo
    container_name: lifeapp-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=Kljukec123
    volumes:
      - mongo-data:/data/db
    networks:
      lifeapp-network:
        ipv4_address: 10.130.210.3

networks:
  lifeapp-network:
    name: lifeapp-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.130.210.0/16

volumes:
  mongo-data:
    name: lifeapp-mongo-data
