version: "3.8"
services:
  api:
    container_name: lifeapp-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./api:/usr/src/app
    networks:
      - lifeapp-network
    depends_on:
      - mongo

  frontend:
    container_name: lifeapp-frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro  # Mount your custom Nginx configuration
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount your Let's Encrypt certificates
    networks:
      - lifeapp-network

  mongo:
    image: mongo
    container_name: lifeapp-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=Kljukec123
    volumes:
      - mongo-data:/data/db
    networks:
      - lifeapp-network

networks:
  lifeapp-network:
    name: lifeapp-network
    driver: bridge

volumes:
  mongo-data:
    name: lifeapp-mongo-data
