# deploy.yml
---
- name: Deploy application to server
  hosts: 134.209.255.8
  become: yes

  tasks:
    - name: Git pull latest code
      git:
        repo: 'https://github.com/MaticMermolja/harmony.git'
        dest: /opt/lifeapp
        version: main
        force: yes

    - name: Install dependencies for API
      npm:
        path: /opt/lifeapp/api

    - name: Install dependencies for Frontend
      npm:
        path: /opt/lifeapp/front

    - name: Build the Angular application
      command: npm run ng build -- --prod
      args:
        chdir: /opt/lifeapp/front

    - name: Rebuild and restart Docker containers
      docker_compose:
        project_src: /opt/lifeapp
        build: yes
        recreate: smart
        restart: yes
